linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/umairsali07/clashm)
      - default
  staticcheck:
    go: '1.21'
